reviews:  
  article_type: !!python/tuple
    - music
    - sports
  fields_to_translate: !!python/tuple
    - title
    - pros_text
    - cons_text
    - text
descriptions: 
  article_type: !!python/tuple
    - design
  fields_to_translate: !!python/tuple
    - content
